### ISSUE TITLE
Docker image is not building

### ISSUE THREAD

**Issue by Murat-U-Saglam** [deadbits/vigil-llm#46]
**Describe the bug**
When building the container I get the following error.

Processing /app/data/datasets/vigil-jailbreak-ada-002/embeddings.parquet...
Traceback (most recent call last):
  File "/app/vigil-server.py", line 10, in <module>
    from flask import Flask, request, jsonify, abort
  File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)

**To Reproduce**
As per - https://vigil.deadbits.ai/overview/install-vigil/docker-quick-start
git clone https://github.com/deadbits/vigil-llm
cd vigil-llm
docker build -t vigil .

# set your openai_api_key in docker.conf
vim conf/docker.conf

docker run -v `pwd`/conf/docker.conf:/app/conf/server.conf -p5000:5000 vigil

**Expected behavior**
Build the image

**Screenshots**
![image](https://github.com/deadbits/vigil-llm/assets/42717642/bb355e6d-b52c-4e99-9107-e86d08d21d16)

**Environment:**
- Vigil version - https://github.com/deadbits/vigil-llm/commit/23ef772e577d9afb05a0977ec91577baa14fc664

**Comment by deadbits** [comment]
Thanks for opening this issue! I’ll take a look at this deeper tomorrow and I should have a fix pushed pretty quickly. It looks like the requirements.txt file might be missing a library or have some conflict that’s causing the error.

**Comment by deadbits** [comment]
Hey @Murat-U-Saglam , sorry this took so long but it should be fixed now!

The issue you found was due to an oudated Flask library. I've fixed this and some other dependency issues, so should be good now.

I've also pushed several other updates since then, including making the data loading process in the Docker entrypoint much easier.

Let me know if you run into any more problems! Thanks again for the report :+1: 

- https://github.com/deadbits/vigil-llm/commit/7e1f45a2687721dbee22c126acb1d69b68840da4
- https://github.com/deadbits/vigil-llm/commit/8b3228e6806e77b2423491548c166cca932d0481
